language: python
python:
    - "2.7"
    - "pypy"
install:
    - |
        if [[ "${TRAVIS_PYTHON_VERSION}" = pypy ]]; then
            git clone https://github.com/yyuu/pyenv.git ~/.pyenv
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            pyenv install pypy-5.4.1
            pyenv global pypy-5.4.1
            pip install git+https://bitbucket.org/pypy/numpy.git
            pip install -r pypy-requirements.txt
        else
            pip install -r py27-requirements.txt
        fi
    - pip install tox-travis
script:
    - tox

after_success:
    - coveralls
